### ISSUE TITLE
wc-api/v3 not working via wc-api-java

### ISSUE THREAD

**Issue by vladislavXXL** [icoderman/wc-api-java#4]
woocommerce version: 3.3.3
wordpress version 4.9.4
wc-api-java version 1.2
I tried to work with wc-api/v1 and wc-api/v2 via postman and they are not works. Only wc-api/v3 works fine with my site. But when I tried to use java library wc-api-java 1.2 (https://github.com/icoderman/wc-api-java):

```
OAuthConfig config = new OAuthConfig(
        "http://URL",
        "ck_XXX",
        "cs_XXX"
);
WooCommerce wooCommerce = new WooCommerceAPI(config, ApiVersionType.V2);

// Prepare object for request
Map<String, Object> productInfo = new HashMap<String, Object>();
productInfo.put("name", "Premium Quality");
productInfo.put("type", "simple");
productInfo.put("regular_price", "21.99");
productInfo.put("description", "This field contains description info.");

//Make request and retrieve result
Map product = wooCommerce.create(EndpointBaseType.PRODUCTS.getValue(), productInfo);

System.out.println(product.get("id"));

// Get all with request parameters
Map<String, String> params = new HashMap<String, String>();
params.put("per_page","100");
params.put("offset","0");
List products = wooCommerce.getAll(EndpointBaseType.PRODUCTS.getValue(), params);

System.out.println(products.size());

```
**Got an exception:**

```
Exception in thread "main" java.lang.NoClassDefFoundError: org/apache/http/client/methods/HttpRequestBase
    at com.icoderman.woocommerce.WooCommerceAPI.<init>(WooCommerceAPI.java:21)
    at Main.main(Main.java:21)
Caused by: java.lang.ClassNotFoundException: org.apache.http.client.methods.HttpRequestBase
    at java.net.URLClassLoader.findClass(URLClassLoader.java:381)
    at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
    at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:335)
    at java.lang.ClassLoader.loadClass(ClassLoader.java:357)

```

Where is no way to use wc-api/v3?

**Comment by icoderman** [comment]
Hi @vladislavXXL, when you are speaking about v3 which one do you mean from the list: http://woocommerce.github.io/woocommerce-rest-api-docs/ ?

Regarding your error, the problem is with httpclient. Do you have dependency on httpclient library in your project (direct or transient)? If yes, please check which version do you use and if it's not the latest version try to use the latest one.

**Comment by vladislavXXL** [comment]
Hello, solved with adding apache httpclient dependency: 

        <dependency>
            <groupId>org.apache.httpcomponents</groupId>
            <artifactId>httpclient</artifactId>
            <version>4.5.5</version>
        </dependency>
