### ISSUE TITLE
Is this save for production due to http?

### ISSUE THREAD

**Issue by NG-Bullseye** [icoderman/wc-api-java#45]
I would like to access a WordPress website in from an Azure Spring app. Due to the http protocol and the older oauth1 standard, is this something to use for a company? Or is the http wrapped in https from azure anyway? I am confused. I would like to have a save connection between the WooCommerce website and my Java application.

**Comment by aabalke** [comment]
According to the [woocommerce api docs](https://woocommerce.github.io/woocommerce-rest-api-docs/?shell#authentication-over-http). OAuth 1.0 is the only (mentioned) supported authentication standard. They do suggest HTTP Basic Auth for HTTPS. Please check out this documentation on the [OAuth standard](https://datatracker.ietf.org/doc/html/rfc5849).
