### ISSUE TITLE
Custom fields

### ISSUE THREAD

**Issue by PrarthanaHegde** [icoderman/wc-api-java#5]
How to add custom or meta fields to product?

**Comment by icoderman** [comment]
Hi @PrarthanaHegde, probably you can use "meta_data" property in the productInfo map. Take a look on http://woocommerce.github.io/woocommerce-rest-api-docs/#product-properties

**Comment by guilherme-oliveria** [comment]
List<Map<String, Object>> metaData= (List<Map<String,Object>>) mapProductIntegracao.get("meta_data");

**Comment by PrarthanaHegde** [comment]
Working fine.Thank you so much.

<https://www.avast.com/sig-email?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail>
Virus-free.
www.avast.com
<https://www.avast.com/sig-email?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail>
<#DAB4FAD8-2DD7-40BB-A1B8-4E2AA1F9FDF2>

On Fri, Mar 16, 2018 at 6:45 PM, Guilherme Machado <notifications@github.com
