### ISSUE TITLE
Support for product variations

### ISSUE THREAD

**Issue by dcoturel** [icoderman/wc-api-java#9]
Hi,
I downloaded this lib in order to work with a WooCommerce site. In this case, we are using variations functionality, so I added a little bit of extra logic. This is what I've done:

EndpointBaseType.java

Added this line:
PRODUCTS_VARIATIONS("products/:product_id/variations"),

WooCommerceAPI.java

Added this function at the end of the class:

private String processEndpointBase(String epb, Map<String, Object> object) {
    	String retval = epb;
    	if (retval.equals("products/:product_id/variations")) {
    		if (object.get("product_id")!=null) {
    			retval = retval.replace(":product_id", object.get("product_id").toString());
    		}
    	}
    	return(retval);
    }

Modified this functions:

@Override
    public Map create(String endpointBase, Map<String, Object> object) {
        String url = String.format(API_URL_FORMAT, config.getUrl(), apiVersion, processEndpointBase(endpointBase, object));
        return client.post(url, OAuthSignature.getAsMap(config, url, HttpMethod.POST), object);
    }

    @Override
    public Map update(String endpointBase, int id, Map<String, Object> object) {
        String url = String.format(API_URL_ONE_ENTITY_FORMAT, config.getUrl(), apiVersion, processEndpointBase(endpointBase, object), id);
        return client.put(url, OAuthSignature.getAsMap(config, url, HttpMethod.PUT), object);
    }

I tell you about this because it might be a starting point to add this functionality, and if it is necesary I can add some code.

This is my first time contributing to an existing project so I don't really know how.

Regards,

**Comment by icoderman** [comment]
Hi @dcoturel, I think it is possible to work with product variations without modification the library, isn't it?
For example:
```java
Map productVariation = wooCommerce.create(String.format("products/%d/variations", 1), productVariationInfo);
```
There is no requirement to use EndpointBaseType, you can use Strings.

**Comment by dcoturel** [comment]
Hi!
Thanks for your answer.
I haven't realized that I could pass the URL, will use it this way.

**Comment by icoderman** [comment]
No problem :)
